Description: Stack for creating EFS File System

Resources:
  efsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group for EC2 to access EFS'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '2049'
          ToPort: '2049'
          CidrIp: '0.0.0.0/0'  # Allow all inbound connections on port 2049 (NFS)

  EFSFileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      PerformanceMode: 'generalPurpose'
      Encrypted: true 

  EFSMountTarget1:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !ImportValue AZStack:PrivateSubnet1
      SecurityGroups:
        - !Ref efsSecurityGroup

  EFSMountTarget2:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !ImportValue AZStack:PrivateSubnet2
      SecurityGroups:
        - !Ref efSecurityGroup.GroupId
  
Outputs:
  EFSFileSystemId:
    Description: 'EFS File System ID'
    Value: !Ref EFSFileSystem
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", "EFSFileSystem" ] ]

  EFSMountTarget1:
    Description: 'EFS Mount Target 1'
    Value: !Ref EFSMountTarget1
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", "EFSMountTarget1" ] ]

  EFSMountTarget2:
    Description: 'EFS Mount Target 2'
    Value: !Ref EFSMountTarget2
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", "EFSMountTarget2" ] ]
