Description: Stack for creating EFS File System

Resources:
  SG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group for EC2 to access EFS'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '2049'
          ToPort: '2049'
          CidrIp: '0.0.0.0/0'  # Allow all inbound connections on port 2049 (NFS)

  EFSFileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      PerformanceMode: 'generalPurpose'
      Encrypted: true 

  EFSMountTarget1:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !ImportValue Multi-AZ:MyFirstPrivateSubnet
      SecurityGroups:
        - !GetAtt SG.GroupId
    DependsOn: SG

  EFSMountTarget2:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !ImportValue Multi-AZ:MySecondPrivateSubnet
      SecurityGroups:
        - !GetAtt SG.GroupId
    DependsOn: SG
  
Outputs:
