Description: Stack for creating loadbalancer

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: RDS-export-bucket
      VersioningConfiguration: 
        Status: Enabled
      WebsiteConfiguration: 
      Tags:
        - Key: Purpose
          Value: RDSExport
  
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
      PolicyDocument: 

Outputs: